In [10]:
from STIC_JPL import process_STIC_table, load_ECOv002_calval_STIC_inputs

In [11]:
input_df = load_ECOv002_calval_STIC_inputs()
input_df

,Unnamed: 0,ID,vegetation,climate,STICinst,BESSinst,MOD16inst,PTJPLSMinst,ETinst,ETinstUncertainty,...,KG_climate,CI,canopy_height_meters,COT,AOT,Ca,wind_speed_mps,vapor_gccm,ozone_cm,Rn_Wm2
0,0,US-NC3,ENF,Cfa,270.345200,78.53355,392.851840,307.021970,487.383423,118.916280,...,3,0.282353,20.642902,0,0,400,0,0,0.3,393.85710
1,1,US-Mi3,CVM,Dfb,232.141600,229.20093,640.118470,375.089300,106.825577,167.919460,...,4,0.286275,0.000000,0,0,400,0,0,0.3,643.47500
2,2,US-Mi3,CVM,Dfb,356.355740,335.23154,625.661700,284.686250,NaN,132.936340,...,4,0.286275,0.000000,0,0,400,0,0,0.3,628.76870
3,3,US-Mi3,CVM,Dfb,332.938400,326.68680,624.254330,251.414490,178.827545,141.132420,...,4,0.286275,0.000000,0,0,400,0,0,0.3,626.95960
4,4,US-Mi3,CVM,Dfb,286.854030,237.21654,511.082180,228.520170,154.791626,114.809410,...,4,0.286275,0.000000,0,0,400,0,0,0.3,513.13380
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,1060,US-xAE,GRA,Cfa,70.923310,172.37459,81.645230,15.282976,NaN,56.385185,...,3,0.301961,0.000000,0,0,400,0,0,0.3,163.24739
1061,1061,US-xAE,GRA,Cfa,116.543190,121.81641,65.469320,22.186659,NaN,40.509410,...,3,0.301961,0.000000,0,0,400,0,0,0.3,166.19196
1062,1062,US-xAE,GRA,Cfa,129.880100,0.00000,118.777240,55.343586,NaN,52.403820,...,3,0.301961,0.000000,0,0,400,0,0,0.3,235.88159
1063,1063,US-xAE,GRA,Cfa,2.707851,140.38632,126.490524,40.434025,NaN,57.769722,...,3,0.301961,0.000000,0,0,400,0,0,0.3,247.87890
1064,1064,US-xAE,GRA,Cfa,303.242950,0.00000,271.749480,119.763630,190.823303,122.092445,...,3,0.301961,0.000000,0,0,400,0,0,0.3,544.22034

In [12]:
processed_df = process_STIC_table(input_df)
processed_df

[2026-03-12 12:14:01 INFO] started extracting geometry from PT-JPL-SM input table
[2026-03-12 12:14:01 INFO] completed extracting geometry from PT-JPL-SM input table
[2026-03-12 12:14:01 INFO] started extracting time from PT-JPL-SM input table
[2026-03-12 12:14:01 INFO] completed extracting time from PT-JPL-SM input table
[2026-03-12 12:14:01 INFO] variable Ms min: 0.000 mean: 0.229 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 1 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 1.262
[2026-03-12 12:14:01 INFO] completed STIC iteration 1 / 30 with max LE change: 309.947 (0.0028232079930603504 seconds)
[2026-03-12 12:14:01 INFO] variable SM_1 min: 0.000 mean: 0.143 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_1 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_1 min: 0.000 mean: 201.081 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 2 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 1.518
[2026-03-12 12:14:01 INFO] completed STIC iteration 2 / 30 with max LE change: 92.3 (0.009626457991544157 seconds)
[2026-03-12 12:14:01 INFO] variable SM_2 min: 0.000 mean: 0.146 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_2 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_2 min: 0.000 mean: 203.532 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 3 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 2.162
[2026-03-12 12:14:01 INFO] completed STIC iteration 3 / 30 with max LE change: 45.001 (0.0139192909700796 seconds)
[2026-03-12 12:14:01 INFO] variable SM_3 min: 0.000 mean: 0.143 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_3 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_3 min: 0.000 mean: 205.475 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 4 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 2.967
[2026-03-12 12:14:01 INFO] completed STIC iteration 4 / 30 with max LE change: 37.126 (0.019389999972190708 seconds)
[2026-03-12 12:14:01 INFO] variable SM_4 min: 0.000 mean: 0.142 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_4 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_4 min: 0.000 mean: 206.992 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 5 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 3.591
[2026-03-12 12:14:01 INFO] completed STIC iteration 5 / 30 with max LE change: 27.957 (0.02390820800792426 seconds)
[2026-03-12 12:14:01 INFO] variable SM_5 min: 0.000 mean: 0.142 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_5 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_5 min: 0.000 mean: 208.208 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 6 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 3.953
[2026-03-12 12:14:01 INFO] completed STIC iteration 6 / 30 with max LE change: 15.006 (0.02881300001172349 seconds)
[2026-03-12 12:14:01 INFO] variable SM_6 min: 0.000 mean: 0.142 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_6 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_6 min: 0.000 mean: 209.135 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 7 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.158
[2026-03-12 12:14:01 INFO] completed STIC iteration 7 / 30 with max LE change: 105.806 (0.03419516596477479 seconds)
[2026-03-12 12:14:01 INFO] variable SM_7 min: 0.000 mean: 0.141 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_7 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_7 min: 0.000 mean: 209.796 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 8 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.266
[2026-03-12 12:14:01 INFO] completed STIC iteration 8 / 30 with max LE change: 145.048 (0.04836999997496605 seconds)
[2026-03-12 12:14:01 INFO] variable SM_8 min: 0.000 mean: 0.141 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_8 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_8 min: 0.000 mean: 210.165 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 9 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.343
[2026-03-12 12:14:01 INFO] completed STIC iteration 9 / 30 with max LE change: 111.489 (0.0663427910185419 seconds)
[2026-03-12 12:14:01 INFO] variable SM_9 min: 0.000 mean: 0.141 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_9 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_9 min: 0.000 mean: 210.781 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 10 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.411
[2026-03-12 12:14:01 INFO] completed STIC iteration 10 / 30 with max LE change: 119.497 (0.07367374998284504 seconds)
[2026-03-12 12:14:01 INFO] variable SM_10 min: 0.000 mean: 0.141 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_10 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_10 min: 0.000 mean: 210.988 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 11 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.432
[2026-03-12 12:14:01 INFO] completed STIC iteration 11 / 30 with max LE change: 73.148 (0.08948841597884893 seconds)
[2026-03-12 12:14:01 INFO] variable SM_11 min: 0.000 mean: 0.141 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_11 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_11 min: 0.000 mean: 211.142 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 12 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.519
[2026-03-12 12:14:01 INFO] completed STIC iteration 12 / 30 with max LE change: 6.588 (0.09420945798046887 seconds)
[2026-03-12 12:14:01 INFO] variable SM_12 min: 0.000 mean: 0.141 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_12 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_12 min: 0.000 mean: 211.440 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 13 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.497
[2026-03-12 12:14:01 INFO] completed STIC iteration 13 / 30 with max LE change: 62.865 (0.1120086659793742 seconds)
[2026-03-12 12:14:01 INFO] variable SM_13 min: 0.000 mean: 0.141 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_13 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_13 min: 0.000 mean: 211.636 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 14 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.505
[2026-03-12 12:14:01 INFO] completed STIC iteration 14 / 30 with max LE change: 111.489 (0.11837174999527633 seconds)
[2026-03-12 12:14:01 INFO] variable SM_14 min: 0.000 mean: 0.141 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_14 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_14 min: 0.000 mean: 211.961 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 15 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.496
[2026-03-12 12:14:01 INFO] completed STIC iteration 15 / 30 with max LE change: 111.489 (0.12473275000229478 seconds)
[2026-03-12 12:14:01 INFO] variable SM_15 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_15 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_15 min: 0.000 mean: 212.081 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 16 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.595
[2026-03-12 12:14:01 INFO] completed STIC iteration 16 / 30 with max LE change: 30.522 (0.13169833301799372 seconds)
[2026-03-12 12:14:01 INFO] variable SM_16 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_16 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_16 min: 0.000 mean: 212.229 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 17 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.524
[2026-03-12 12:14:01 INFO] completed STIC iteration 17 / 30 with max LE change: 48.084 (0.14166558301076293 seconds)
[2026-03-12 12:14:01 INFO] variable SM_17 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_17 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_17 min: 0.000 mean: 212.334 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 18 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.541
[2026-03-12 12:14:01 INFO] completed STIC iteration 18 / 30 with max LE change: 35.098 (0.15082091599470004 seconds)
[2026-03-12 12:14:01 INFO] variable SM_18 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_18 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_18 min: 0.000 mean: 212.501 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 19 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.528
[2026-03-12 12:14:01 INFO] completed STIC iteration 19 / 30 with max LE change: 111.489 (0.16109141596825793 seconds)
[2026-03-12 12:14:01 INFO] variable SM_19 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable G_19 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] variable LE_19 min: 0.000 mean: 212.737 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:01 INFO] running STIC iteration 20 / 30
[2026-03-12 12:14:01 INFO] using variable Priestley-Taylor alpha with mean: 4.522
[2026-03-12 12:14:01 INFO] completed STIC iteration 20 / 30 with max LE change: 136.453 (0.16855841601500288 seconds)
[2026-03-12 12:14:01 INFO] variable SM_20 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable G_20 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable LE_20 min: 0.000 mean: 212.567 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] running STIC iteration 21 / 30
[2026-03-12 12:14:02 INFO] using variable Priestley-Taylor alpha with mean: 4.55
[2026-03-12 12:14:02 INFO] completed STIC iteration 21 / 30 with max LE change: 35.02 (0.1782049160101451 seconds)
[2026-03-12 12:14:02 INFO] variable SM_21 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable G_21 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable LE_21 min: 0.000 mean: 212.699 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] running STIC iteration 22 / 30
[2026-03-12 12:14:02 INFO] using variable Priestley-Taylor alpha with mean: 4.562
[2026-03-12 12:14:02 INFO] completed STIC iteration 22 / 30 with max LE change: 13.064 (0.1867302079917863 seconds)
[2026-03-12 12:14:02 INFO] variable SM_22 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable G_22 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable LE_22 min: 0.000 mean: 212.799 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] running STIC iteration 23 / 30
[2026-03-12 12:14:02 INFO] using variable Priestley-Taylor alpha with mean: 4.576
[2026-03-12 12:14:02 INFO] completed STIC iteration 23 / 30 with max LE change: 48.084 (0.19394795800326392 seconds)
[2026-03-12 12:14:02 INFO] variable SM_23 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable G_23 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable LE_23 min: 0.000 mean: 212.833 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] running STIC iteration 24 / 30
[2026-03-12 12:14:02 INFO] using variable Priestley-Taylor alpha with mean: 4.556
[2026-03-12 12:14:02 INFO] completed STIC iteration 24 / 30 with max LE change: 111.489 (0.20106649998342618 seconds)
[2026-03-12 12:14:02 INFO] variable SM_24 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable G_24 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable LE_24 min: 0.000 mean: 213.042 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] running STIC iteration 25 / 30
[2026-03-12 12:14:02 INFO] using variable Priestley-Taylor alpha with mean: 4.571
[2026-03-12 12:14:02 INFO] completed STIC iteration 25 / 30 with max LE change: 111.489 (0.20887183299055323 seconds)
[2026-03-12 12:14:02 INFO] variable SM_25 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable G_25 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable LE_25 min: 0.000 mean: 213.015 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] running STIC iteration 26 / 30
[2026-03-12 12:14:02 INFO] using variable Priestley-Taylor alpha with mean: 4.565
[2026-03-12 12:14:02 INFO] completed STIC iteration 26 / 30 with max LE change: 48.084 (0.21643016597954556 seconds)
[2026-03-12 12:14:02 INFO] variable SM_26 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable G_26 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable LE_26 min: 0.000 mean: 213.030 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] running STIC iteration 27 / 30
[2026-03-12 12:14:02 INFO] using variable Priestley-Taylor alpha with mean: 4.575
[2026-03-12 12:14:02 INFO] completed STIC iteration 27 / 30 with max LE change: 35.018 (0.22597566596232355 seconds)
[2026-03-12 12:14:02 INFO] variable SM_27 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable G_27 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable LE_27 min: 0.000 mean: 213.118 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] running STIC iteration 28 / 30
[2026-03-12 12:14:02 INFO] using variable Priestley-Taylor alpha with mean: 4.585
[2026-03-12 12:14:02 INFO] completed STIC iteration 28 / 30 with max LE change: 13.066 (0.2349398749647662 seconds)
[2026-03-12 12:14:02 INFO] variable SM_28 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable G_28 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable LE_28 min: 0.000 mean: 213.179 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] running STIC iteration 29 / 30
[2026-03-12 12:14:02 INFO] using variable Priestley-Taylor alpha with mean: 4.531
[2026-03-12 12:14:02 INFO] completed STIC iteration 29 / 30 with max LE change: 111.489 (0.24083116598194465 seconds)
[2026-03-12 12:14:02 INFO] variable SM_29 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable G_29 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable LE_29 min: 0.000 mean: 213.284 max: 640.944 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] running STIC iteration 30 / 30
[2026-03-12 12:14:02 INFO] using variable Priestley-Taylor alpha with mean: 4.581
[2026-03-12 12:14:02 INFO] completed STIC iteration 30 / 30 with max LE change: 111.489 (0.24626729101873934 seconds)
[2026-03-12 12:14:02 INFO] variable SM_30 min: 0.000 mean: 0.140 max: 1.000 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable G_30 min: 0.000 mean: 51.339 max: 158.322 nan: 0.00% (nan)
[2026-03-12 12:14:02 INFO] variable LE_30 min: 0.000 mean: 213.253 max: 640.944 nan: 0.00% (nan)

,Unnamed: 0,ID,vegetation,climate,STICinst,BESSinst,MOD16inst,PTJPLSMinst,ETinst,ETinstUncertainty,...,Rn_Wm2,LE_max_change,iteration,LE_Wm2,LE_change,LE_soil_Wm2,LE_canopy_Wm2,PT,PET_Wm2,G_Wm2
0,0,US-NC3,ENF,Cfa,270.345200,78.53355,392.851840,307.021970,487.383423,118.916280,...,393.85710,111.489119,30,342.855573,0.000000e+00,121.685905,221.169668,567.485731,657.068870,51.001527
1,1,US-Mi3,CVM,Dfb,232.141600,229.20093,640.118470,375.089300,106.825577,167.919460,...,643.47500,111.489119,30,296.642167,2.960982e-05,31.172221,265.469946,588.371652,620.648756,81.309890
2,2,US-Mi3,CVM,Dfb,356.355740,335.23154,625.661700,284.686250,NaN,132.936340,...,628.76870,111.489119,30,385.908982,5.291795e-04,81.212847,304.696135,523.216242,557.043751,80.764205
3,3,US-Mi3,CVM,Dfb,332.938400,326.68680,624.254330,251.414490,178.827545,141.132420,...,626.95960,111.489119,30,308.062971,2.724916e-05,43.219559,264.843411,523.621124,556.409634,64.855799
4,4,US-Mi3,CVM,Dfb,286.854030,237.21654,511.082180,228.520170,154.791626,114.809410,...,513.13380,111.489119,30,242.923841,1.939832e-05,30.812421,212.111420,436.072576,462.320910,58.296844
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,1060,US-xAE,GRA,Cfa,70.923310,172.37459,81.645230,15.282976,NaN,56.385185,...,163.24739,111.489119,30,87.860637,2.417619e-02,40.536864,47.323774,171.282626,218.536892,4.103044
1061,1061,US-xAE,GRA,Cfa,116.543190,121.81641,65.469320,22.186659,NaN,40.509410,...,166.19196,111.489119,30,128.486743,1.246224e-01,33.425348,95.061395,221.343278,249.240867,15.442521
1062,1062,US-xAE,GRA,Cfa,129.880100,0.00000,118.777240,55.343586,NaN,52.403820,...,235.88159,111.489119,30,6.145779,0.000000e+00,0.000000,6.145779,2439.466245,2439.466245,30.976170
1063,1063,US-xAE,GRA,Cfa,2.707851,140.38632,126.490524,40.434025,NaN,57.769722,...,247.87890,111.489119,30,68.889929,9.457331e-08,15.415533,53.474396,195.854129,226.341378,19.863577
1064,1064,US-xAE,GRA,Cfa,303.242950,0.00000,271.749480,119.763630,190.823303,122.092445,...,544.22034,111.489119,30,221.054027,8.773241e-06,13.243034,207.810993,455.577749,470.035062,104.388516

In [13]:
processed_df[["Rn_Wm2", "G_Wm2", "LE_Wm2", "PET_Wm2"]]

         Rn_Wm2       G_Wm2      LE_Wm2      PET_Wm2
0     393.85710   51.001527  342.855573   657.068870
1     643.47500   81.309890  296.642167   620.648756
2     628.76870   80.764205  385.908982   557.043751
3     626.95960   64.855799  308.062971   556.409634
4     513.13380   58.296844  242.923841   462.320910
...         ...         ...         ...          ...
1060  163.24739    4.103044   87.860637   218.536892
1061  166.19196   15.442521  128.486743   249.240867
1062  235.88159   30.976170    6.145779  2439.466245
1063  247.87890   19.863577   68.889929   226.341378
1064  544.22034  104.388516  221.054027   470.035062

[1065 rows x 4 columns]

In [14]:
processed_df.PET_Wm2 / processed_df.LE_Wm2

0         1.916460
1         2.092247
2         1.443459
3         1.806156
4         1.903152
           ...
1060      2.487313
1061      1.939818
1062    396.933620
1063      3.285551
1064      2.126336
Length: 1065, dtype: float64